#!/usr/bin/env sh

# Rodar phpstan
./vendor/bin/phpstan
if [ $? -ne 0 ]
then
    echo "Opa! Deu ruim em algum arquivo ao rodar a análise sintática! Arrume antes de continuar."
    exit 1
fi

# Formatar cada arquivo alterado usando pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true
for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}"
    git add "${FILE}"
done

exit 0